name: Build plz_wert.json from Google Sheet

on:
  schedule:
    - cron: '0 3 * * *'        # täglich um 03:00 Uhr
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Google Sheet (VNB → Wert)
        run: curl -L "https://docs.google.com/spreadsheets/d/1huo96_hM_yGc8nIZ9KMzpIPuNHfQR6uQU-NnAloHGuQ/export?format=csv" -o data/input.csv

      - name: Install Python
        run: sudo apt-get install -y python3 python3-pip

      - name: Convert Google Sheet + Mapping to plz_wert.json
        run: |
          python3 <<EOF
import csv
import json
import os

# Pfade
vnb_wert_csv = 'data/input.csv'
plz_vnb_json = 'data/plz_vnb.json'
plz_wert_json = 'data/plz_wert.json'

# Laden: VNB → Wert
vnb_to_value = {}
with open(vnb_wert_csv, newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        vnb = row.get('VNB', '').strip()
        wert = row.get('Wert', '').strip()
        if vnb and wert:
            try:
                vnb_to_value[vnb] = float(wert)
            except ValueError:
                continue  # ungültiger Wert, überspringen

# Laden: PLZ → VNB
if not os.path.exists(plz_vnb_json):
    raise FileNotFoundError(f"{plz_vnb_json} fehlt!")

with open(plz_vnb_json, encoding='utf-8') as f:
    plz_to_vnb = json.load(f)

# Kombinieren: PLZ → Wert (über VNB)
plz_to_value = {}
for plz, vnb in plz_to_vnb.items():
    value = vnb_to_value.get(vnb)
    if value is not None:
        plz_to_value[plz] = value

# Speichern
with open(plz_wert_json, 'w', encoding='utf-8') as f:
    json.dump(plz_to_value, f, indent=2, ensure_ascii=False)
EOF

      - name: Commit JSON file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git add data/plz_wert.json
          git commit -m "Auto-update plz_wert.json from Google Sheets" || echo "No changes"
          git push
